### ISSUE TITLE
mu did not add/change uuid in v2ray api after uuid has been change

### ISSUE THREAD

**Issue by shuangzhijinghua** [orvice/v2ray-mu#5]
example : 
UID 1 have a UUID : `1-1-1-1-1`, then user UID 1 change his UUID to `1-1-1-1-2`, new UUID will not available until mu program has been restart, old UUID still usable.

**Comment by orvice** [comment]
there's no prefect solution to deal this problem, if uuid change, you should restart v2ray-mu and v2ray.
